<a href="https://colab.research.google.com/github/Lucaavnt/MLDM2026_exercises/blob/main/VL735753_03_Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Practice - Hints - Unibs 2021

#### Import the numpy package under the name `np` and print version and configuration (base)
`hint: import … as, np.__version__, np.show_config`

In [10]:
import numpy as np
print(f"NumPy version: {np.__version__}\n")
print("*---- Configuration ----*")
np.show_config()

NumPy version: 2.0.2

*---- Configuration ----*
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
  

## Base Practice

#### 1. Create a null vector of size 10 but the fifth value which is 1 (base)
`hint: array[4]`

In [24]:
nullVector = np.zeros(10)
nullVector[4] = 1

nullVector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 2. Create a 3x3 matrix with values ranging from 0 to 8 with zeros on the diagonal (base)
`hint: np.arange, reshape, np.eye`

In [25]:
M = np.reshape(np.arange(0,9),(3,3))
M = M - M*np.eye(3,3)
M

array([[0., 1., 2.],
       [3., 0., 5.],
       [6., 7., 0.]])

#### 3. How to add a border (filled with 0's) around an 5x5 matrix of ones? (base)
`hint: np.ones, np.pad`

In [42]:
Z = np.ones((5,5))
Z_padded = np.pad(Z,1,'constant',constant_values=0)

Z_padded

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 4. Normalize a 5x5 random matrix (base)
`hint: (x - mean) / std, np.mean, np.std`

In [60]:
R = np.random.rand(5,5)
mean = np.mean(R)
std = np.std(R)
R_norm = (R - mean)/std

R_norm

array([[ 0.36438339, -0.61146175,  1.54691096,  0.54217837, -1.24026017],
       [-0.16958389,  0.43084956, -0.91391944,  0.06417407, -0.32164355],
       [ 0.65410948, -1.20756712,  1.62739409, -1.3218672 ,  1.49887123],
       [-0.83864028, -0.61769043, -0.74901668,  0.52092   , -0.60267276],
       [-0.07180104, -1.00831656,  2.51996424,  0.63259178, -0.72790632]])

#### 5. Multiply a 5x3 matrix of ones by a 3x2 matrix of ones (real matrix product) (base)
`hint: np.dot`

In [62]:
A = np.ones((5,3))
B = np.ones((3,2))
P = np.dot(A,B)

P

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

## Intermediate Practice

#### 6. Create a vector of size 10 with values ranging from 0 to 1, both excluded (intermediate)
`hint: np.linspace`

In [67]:
v = np.linspace(0,1,12)[1:-1]

v

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 7. Create a random vector of size 10 with values in range (-3, 12) and sort it (intermediate)
`hint: sort`

In [75]:
randomVector_sorted = np.sort((np.random.rand(10) * 15) - 3)

randomVector_sorted

array([-2.30143241, -1.38642691, -1.09663102, -0.02127586,  0.79416417,
        1.18443988,  1.55019239,  2.34793567,  6.1659543 , 11.91625714])

#### 8. Create random vector of size 10 and replace the maximum value by its additive inverse and the minimum value (of the original array) with the median value (intermediate)
`hint: argmax, argmin`

In [79]:
randomVector = np.random.rand(10)
max_idx = np.argmax(randomVector)
min_idx = np.argmin(randomVector)
median = np.median(randomVector)

print(f"Original vector: {randomVector}")
print(f"max idx = {max_idx}, min idx = {min_idx}")

randomVector[max_idx] = -randomVector[max_idx]
randomVector[min_idx] = median

print(f"\nModified vector: {randomVector}")


Original vector: [0.23900382 0.416374   0.17489861 0.90588943 0.0817237  0.33769476
 0.3056999  0.64696572 0.0512111  0.54928566]
max idx = 3, min idx = 8

Modified vector: [ 0.23900382  0.416374    0.17489861 -0.90588943  0.0817237   0.33769476
  0.3056999   0.64696572  0.32169733  0.54928566]


#### 9. Randomly replace p elements in a 2D nxn zero matrix to 1 (intermediate)
`hint: np.put, np.random.choice`

In [96]:
n = int(input("Insert n: "))
p = int(input("Insert p: "))

assert p <= n**2

zeroMatrix = np.zeros((n,n))

idxs = np.random.choice(range(0,n**2),p,replace=False)

np.put(zeroMatrix,idxs,np.ones(p))

zeroMatrix


Insert n: 5
Insert p: 13


array([[1., 1., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 0.],
       [0., 0., 0., 1., 0.]])

#### 10. Subtract the mean of each row of a random 5x10 matrix (intermediate)
`hint: mean(axis=,keepdims=)`

In [109]:
randomMatrix = np.random.rand(5,10)
print("*- Original matrix -*")
print(randomMatrix)

means = np.mean(randomMatrix,axis=1,keepdims=True)
print("\n*- Row means -*")
print(np.reshape(means,(-1,1)))

randomMatrix_sub = randomMatrix - means
print("\n*- Modified matrix -*")
print(randomMatrix_sub)

*- Original matrix -*
[[0.07391411 0.46387603 0.54299205 0.55936704 0.48286259 0.92624687
  0.90027252 0.8193714  0.81831711 0.74208894]
 [0.035511   0.14262028 0.64399374 0.54752627 0.19243026 0.47205149
  0.13243901 0.52346025 0.20298491 0.70969149]
 [0.55757362 0.90603286 0.32746515 0.34614782 0.35425751 0.20533033
  0.41670886 0.17930002 0.04290877 0.89019581]
 [0.90641495 0.91788072 0.87359739 0.32114393 0.79501262 0.72799432
  0.72559826 0.51240498 0.41619996 0.70115832]
 [0.30909645 0.08768037 0.33118778 0.82302186 0.32709914 0.48084984
  0.32056001 0.18910456 0.06624755 0.90318852]]

*- Row means -*
[[0.63293087]
 [0.36027087]
 [0.42259207]
 [0.68974055]
 [0.38380361]]

*- Modified matrix -*
[[-0.55901676 -0.16905484 -0.08993881 -0.07356382 -0.15006828  0.293316
   0.26734166  0.18644054  0.18538624  0.10915807]
 [-0.32475987 -0.21765059  0.28372287  0.1872554  -0.16784061  0.11178062
  -0.22783186  0.16318938 -0.15728596  0.34942062]
 [ 0.13498155  0.48344078 -0.09512693 -0.07